FROM mcr.microsoft.com/playwright:v1.55.0-noble@sha256:b27e719ecbfef153e13fd24e8341736733bf2658b229677eb21ff57ff5d7fb29

WORKDIR /app

# required by the e2e test code
RUN npm install "@playwright/test@1.55.0" "dotenv@^16.3.1" "@grafana/plugin-e2e" "monocart-reporter"

CMD ["npx", "playwright", "test", "-c", "e2e/playwright.config.ts"]

